"""Add updated_by and updated_at fields to Board

Revision ID: dd396d6573b8
Revises: ed90cc18f54d
Create Date: 2025-02-11 11:56:23.855084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd396d6573b8'
down_revision = 'ed90cc18f54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
